// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/email.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **************************************
//
//	Email entities and types       *
//
// *************************************
type EmailLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	To              []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc              []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc             []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject         string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content         string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Template        string                 `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	Data            string                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"` // JSON string
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg        string                 `protobuf:"bytes,10,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	SentAt          int64                  `protobuf:"varint,11,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	RequestId       string                 `protobuf:"bytes,12,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RetryCount      int32                  `protobuf:"varint,13,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	Headers         string                 `protobuf:"bytes,14,opt,name=headers,proto3" json:"headers,omitempty"` // JSON string
	Response        string                 `protobuf:"bytes,15,opt,name=response,proto3" json:"response,omitempty"`
	Provider        string                 `protobuf:"bytes,16,opt,name=provider,proto3" json:"provider,omitempty"`
	TotalRecipients int32                  `protobuf:"varint,17,opt,name=total_recipients,json=totalRecipients,proto3" json:"total_recipients,omitempty"`
	ContentType     string                 `protobuf:"bytes,18,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	AttachmentCount int32                  `protobuf:"varint,19,opt,name=attachment_count,json=attachmentCount,proto3" json:"attachment_count,omitempty"`
	MessageSize     int64                  `protobuf:"varint,20,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       int64                  `protobuf:"varint,23,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmailLog) Reset() {
	*x = EmailLog{}
	mi := &file_proto_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLog) ProtoMessage() {}

func (x *EmailLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLog.ProtoReflect.Descriptor instead.
func (*EmailLog) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailLog) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailLog) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailLog) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *EmailLog) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailLog) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *EmailLog) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EmailLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmailLog) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *EmailLog) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *EmailLog) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EmailLog) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *EmailLog) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *EmailLog) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *EmailLog) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmailLog) GetTotalRecipients() int32 {
	if x != nil {
		return x.TotalRecipients
	}
	return 0
}

func (x *EmailLog) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EmailLog) GetAttachmentCount() int32 {
	if x != nil {
		return x.AttachmentCount
	}
	return 0
}

func (x *EmailLog) GetMessageSize() int64 {
	if x != nil {
		return x.MessageSize
	}
	return 0
}

func (x *EmailLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EmailLog) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *EmailLog) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type EmailTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Locale        string                 `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplate) Reset() {
	*x = EmailTemplate{}
	mi := &file_proto_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplate) ProtoMessage() {}

func (x *EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplate.ProtoReflect.Descriptor instead.
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailTemplate) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EmailTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailTemplate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EmailTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EmailTemplate) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *EmailTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EmailTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *EmailTemplate) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type EmailAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Inline        bool                   `protobuf:"varint,4,opt,name=inline,proto3" json:"inline,omitempty"`
	ContentId     string                 `protobuf:"bytes,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAttachment) Reset() {
	*x = EmailAttachment{}
	mi := &file_proto_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAttachment) ProtoMessage() {}

func (x *EmailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAttachment.ProtoReflect.Descriptor instead.
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{2}
}

func (x *EmailAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmailAttachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *EmailAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EmailAttachment) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

func (x *EmailAttachment) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

// *********************************************
//
//	Email service request/response       *
//
// ********************************************
type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Attachments   []*EmailAttachment     `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provider      string                 `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_proto_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{3}
}

func (x *SendEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendEmailRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SendEmailRequest) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendEmailRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendEmailRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendEmailRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLog      *EmailLog              `protobuf:"bytes,1,opt,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_proto_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{4}
}

func (x *SendEmailResponse) GetEmailLog() *EmailLog {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

type SendEmailWithTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,4,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Locale        string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Data          string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // JSON string
	Attachments   []*EmailAttachment     `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provider      string                 `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateRequest) Reset() {
	*x = SendEmailWithTemplateRequest{}
	mi := &file_proto_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateRequest) ProtoMessage() {}

func (x *SendEmailWithTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{5}
}

func (x *SendEmailWithTemplateRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailWithTemplateRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailWithTemplateRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailWithTemplateRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendEmailWithTemplateRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendEmailWithTemplateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendEmailWithTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLog      *EmailLog              `protobuf:"bytes,1,opt,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateResponse) Reset() {
	*x = SendEmailWithTemplateResponse{}
	mi := &file_proto_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateResponse) ProtoMessage() {}

func (x *SendEmailWithTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateResponse.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{6}
}

func (x *SendEmailWithTemplateResponse) GetEmailLog() *EmailLog {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

type BulkEmailRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkEmailRecipient) Reset() {
	*x = BulkEmailRecipient{}
	mi := &file_proto_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkEmailRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkEmailRecipient) ProtoMessage() {}

func (x *BulkEmailRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkEmailRecipient.ProtoReflect.Descriptor instead.
func (*BulkEmailRecipient) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{7}
}

func (x *BulkEmailRecipient) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *BulkEmailRecipient) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendBulkEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*BulkEmailRecipient  `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailRequest) Reset() {
	*x = SendBulkEmailRequest{}
	mi := &file_proto_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailRequest) ProtoMessage() {}

func (x *SendBulkEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailRequest.ProtoReflect.Descriptor instead.
func (*SendBulkEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{8}
}

func (x *SendBulkEmailRequest) GetRecipients() []*BulkEmailRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendBulkEmailRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendBulkEmailRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SendBulkEmailRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendBulkEmailRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendBulkEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLogs     []*EmailLog            `protobuf:"bytes,1,rep,name=email_logs,json=emailLogs,proto3" json:"email_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailResponse) Reset() {
	*x = SendBulkEmailResponse{}
	mi := &file_proto_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailResponse) ProtoMessage() {}

func (x *SendBulkEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailResponse.ProtoReflect.Descriptor instead.
func (*SendBulkEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{9}
}

func (x *SendBulkEmailResponse) GetEmailLogs() []*EmailLog {
	if x != nil {
		return x.EmailLogs
	}
	return nil
}

type ResendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLogId    string                 `protobuf:"bytes,1,opt,name=email_log_id,json=emailLogId,proto3" json:"email_log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendEmailRequest) Reset() {
	*x = ResendEmailRequest{}
	mi := &file_proto_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendEmailRequest) ProtoMessage() {}

func (x *ResendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendEmailRequest.ProtoReflect.Descriptor instead.
func (*ResendEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{10}
}

func (x *ResendEmailRequest) GetEmailLogId() string {
	if x != nil {
		return x.EmailLogId
	}
	return ""
}

type ResendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLog      *EmailLog              `protobuf:"bytes,1,opt,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendEmailResponse) Reset() {
	*x = ResendEmailResponse{}
	mi := &file_proto_email_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendEmailResponse) ProtoMessage() {}

func (x *ResendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendEmailResponse.ProtoReflect.Descriptor instead.
func (*ResendEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{11}
}

func (x *ResendEmailResponse) GetEmailLog() *EmailLog {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

type CreateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Locale        string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	IsActive      *bool                  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateRequest) Reset() {
	*x = CreateEmailTemplateRequest{}
	mi := &file_proto_email_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateRequest) ProtoMessage() {}

func (x *CreateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEmailTemplateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type CreateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateResponse) Reset() {
	*x = CreateEmailTemplateResponse{}
	mi := &file_proto_email_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateResponse) ProtoMessage() {}

func (x *CreateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{13}
}

func (x *CreateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateRequest) Reset() {
	*x = GetEmailTemplateRequest{}
	mi := &file_proto_email_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateRequest) ProtoMessage() {}

func (x *GetEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{14}
}

func (x *GetEmailTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateResponse) Reset() {
	*x = GetEmailTemplateResponse{}
	mi := &file_proto_email_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateResponse) ProtoMessage() {}

func (x *GetEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{15}
}

func (x *GetEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetEmailTemplateByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateByCodeRequest) Reset() {
	*x = GetEmailTemplateByCodeRequest{}
	mi := &file_proto_email_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateByCodeRequest) ProtoMessage() {}

func (x *GetEmailTemplateByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateByCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{16}
}

func (x *GetEmailTemplateByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetEmailTemplateByCodeRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type GetEmailTemplateByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateByCodeResponse) Reset() {
	*x = GetEmailTemplateByCodeResponse{}
	mi := &file_proto_email_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateByCodeResponse) ProtoMessage() {}

func (x *GetEmailTemplateByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateByCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{17}
}

func (x *GetEmailTemplateByCodeResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Subject       *string                `protobuf:"bytes,3,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Content       *string                `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsActive      *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateRequest) Reset() {
	*x = UpdateEmailTemplateRequest{}
	mi := &file_proto_email_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateRequest) ProtoMessage() {}

func (x *UpdateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEmailTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateResponse) Reset() {
	*x = UpdateEmailTemplateResponse{}
	mi := &file_proto_email_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateResponse) ProtoMessage() {}

func (x *UpdateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailTemplateRequest) Reset() {
	*x = DeleteEmailTemplateRequest{}
	mi := &file_proto_email_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailTemplateRequest) ProtoMessage() {}

func (x *DeleteEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteEmailTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type DeleteEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailTemplateResponse) Reset() {
	*x = DeleteEmailTemplateResponse{}
	mi := &file_proto_email_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailTemplateResponse) ProtoMessage() {}

func (x *DeleteEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteEmailTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListEmailTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Code          *string                `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Locale        *string                `protobuf:"bytes,4,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	IsActive      *bool                  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Search        *string                `protobuf:"bytes,6,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesRequest) Reset() {
	*x = ListEmailTemplatesRequest{}
	mi := &file_proto_email_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesRequest) ProtoMessage() {}

func (x *ListEmailTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{22}
}

func (x *ListEmailTemplatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailTemplatesRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListEmailTemplatesRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *ListEmailTemplatesRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *ListEmailTemplatesRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListEmailTemplatesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type ListEmailTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*EmailTemplate       `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesResponse) Reset() {
	*x = ListEmailTemplatesResponse{}
	mi := &file_proto_email_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesResponse) ProtoMessage() {}

func (x *ListEmailTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{23}
}

func (x *ListEmailTemplatesResponse) GetTemplates() []*EmailTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListEmailTemplatesResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListEmailTemplatesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailTemplatesResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListEmailTemplatesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetEmailLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLogId    string                 `protobuf:"bytes,1,opt,name=email_log_id,json=emailLogId,proto3" json:"email_log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailLogRequest) Reset() {
	*x = GetEmailLogRequest{}
	mi := &file_proto_email_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailLogRequest) ProtoMessage() {}

func (x *GetEmailLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailLogRequest.ProtoReflect.Descriptor instead.
func (*GetEmailLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{24}
}

func (x *GetEmailLogRequest) GetEmailLogId() string {
	if x != nil {
		return x.EmailLogId
	}
	return ""
}

type GetEmailLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLog      *EmailLog              `protobuf:"bytes,1,opt,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailLogResponse) Reset() {
	*x = GetEmailLogResponse{}
	mi := &file_proto_email_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailLogResponse) ProtoMessage() {}

func (x *GetEmailLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailLogResponse.ProtoReflect.Descriptor instead.
func (*GetEmailLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{25}
}

func (x *GetEmailLogResponse) GetEmailLog() *EmailLog {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

type ListEmailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Provider      *string                `protobuf:"bytes,4,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Template      *string                `protobuf:"bytes,5,opt,name=template,proto3,oneof" json:"template,omitempty"`
	AnyRecipient  *string                `protobuf:"bytes,6,opt,name=any_recipient,json=anyRecipient,proto3,oneof" json:"any_recipient,omitempty"`
	Search        *string                `protobuf:"bytes,7,opt,name=search,proto3,oneof" json:"search,omitempty"`
	SentAfter     *int64                 `protobuf:"varint,8,opt,name=sent_after,json=sentAfter,proto3,oneof" json:"sent_after,omitempty"`
	SentBefore    *int64                 `protobuf:"varint,9,opt,name=sent_before,json=sentBefore,proto3,oneof" json:"sent_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailLogsRequest) Reset() {
	*x = ListEmailLogsRequest{}
	mi := &file_proto_email_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailLogsRequest) ProtoMessage() {}

func (x *ListEmailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailLogsRequest.ProtoReflect.Descriptor instead.
func (*ListEmailLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{26}
}

func (x *ListEmailLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailLogsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListEmailLogsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListEmailLogsRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *ListEmailLogsRequest) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *ListEmailLogsRequest) GetAnyRecipient() string {
	if x != nil && x.AnyRecipient != nil {
		return *x.AnyRecipient
	}
	return ""
}

func (x *ListEmailLogsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListEmailLogsRequest) GetSentAfter() int64 {
	if x != nil && x.SentAfter != nil {
		return *x.SentAfter
	}
	return 0
}

func (x *ListEmailLogsRequest) GetSentBefore() int64 {
	if x != nil && x.SentBefore != nil {
		return *x.SentBefore
	}
	return 0
}

type ListEmailLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailLogs     []*EmailLog            `protobuf:"bytes,1,rep,name=email_logs,json=emailLogs,proto3" json:"email_logs,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailLogsResponse) Reset() {
	*x = ListEmailLogsResponse{}
	mi := &file_proto_email_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailLogsResponse) ProtoMessage() {}

func (x *ListEmailLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailLogsResponse.ProtoReflect.Descriptor instead.
func (*ListEmailLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{27}
}

func (x *ListEmailLogsResponse) GetEmailLogs() []*EmailLog {
	if x != nil {
		return x.EmailLogs
	}
	return nil
}

func (x *ListEmailLogsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListEmailLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailLogsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListEmailLogsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetEmailStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *string                `protobuf:"bytes,1,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Template      *string                `protobuf:"bytes,2,opt,name=template,proto3,oneof" json:"template,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	DateFrom      *int64                 `protobuf:"varint,4,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"`
	DateTo        *int64                 `protobuf:"varint,5,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`
	GroupBy       *string                `protobuf:"bytes,6,opt,name=group_by,json=groupBy,proto3,oneof" json:"group_by,omitempty"`
	IncludeTotal  *bool                  `protobuf:"varint,7,opt,name=include_total,json=includeTotal,proto3,oneof" json:"include_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailStatsRequest) Reset() {
	*x = GetEmailStatsRequest{}
	mi := &file_proto_email_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailStatsRequest) ProtoMessage() {}

func (x *GetEmailStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailStatsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{28}
}

func (x *GetEmailStatsRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *GetEmailStatsRequest) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *GetEmailStatsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetEmailStatsRequest) GetDateFrom() int64 {
	if x != nil && x.DateFrom != nil {
		return *x.DateFrom
	}
	return 0
}

func (x *GetEmailStatsRequest) GetDateTo() int64 {
	if x != nil && x.DateTo != nil {
		return *x.DateTo
	}
	return 0
}

func (x *GetEmailStatsRequest) GetGroupBy() string {
	if x != nil && x.GroupBy != nil {
		return *x.GroupBy
	}
	return ""
}

func (x *GetEmailStatsRequest) GetIncludeTotal() bool {
	if x != nil && x.IncludeTotal != nil {
		return *x.IncludeTotal
	}
	return false
}

type EmailStatsGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sent          int64                  `protobuf:"varint,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Success       int64                  `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int64                  `protobuf:"varint,6,opt,name=failed,proto3" json:"failed,omitempty"`
	Pending       int64                  `protobuf:"varint,7,opt,name=pending,proto3" json:"pending,omitempty"`
	Rate          float64                `protobuf:"fixed64,8,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStatsGroup) Reset() {
	*x = EmailStatsGroup{}
	mi := &file_proto_email_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStatsGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStatsGroup) ProtoMessage() {}

func (x *EmailStatsGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStatsGroup.ProtoReflect.Descriptor instead.
func (*EmailStatsGroup) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{29}
}

func (x *EmailStatsGroup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EmailStatsGroup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EmailStatsGroup) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EmailStatsGroup) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *EmailStatsGroup) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *EmailStatsGroup) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *EmailStatsGroup) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *EmailStatsGroup) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type EmailProviderStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	TotalSent     int64                  `protobuf:"varint,2,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,4,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgRetryCount float64                `protobuf:"fixed64,6,opt,name=avg_retry_count,json=avgRetryCount,proto3" json:"avg_retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailProviderStats) Reset() {
	*x = EmailProviderStats{}
	mi := &file_proto_email_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailProviderStats) ProtoMessage() {}

func (x *EmailProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailProviderStats.ProtoReflect.Descriptor instead.
func (*EmailProviderStats) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{30}
}

func (x *EmailProviderStats) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmailProviderStats) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *EmailProviderStats) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *EmailProviderStats) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *EmailProviderStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *EmailProviderStats) GetAvgRetryCount() float64 {
	if x != nil {
		return x.AvgRetryCount
	}
	return 0
}

type EmailTemplateStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TotalSent     int64                  `protobuf:"varint,3,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,4,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,5,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	LastUsed      int64                  `protobuf:"varint,7,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplateStats) Reset() {
	*x = EmailTemplateStats{}
	mi := &file_proto_email_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplateStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplateStats) ProtoMessage() {}

func (x *EmailTemplateStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplateStats.ProtoReflect.Descriptor instead.
func (*EmailTemplateStats) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{31}
}

func (x *EmailTemplateStats) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *EmailTemplateStats) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EmailTemplateStats) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *EmailTemplateStats) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *EmailTemplateStats) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *EmailTemplateStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *EmailTemplateStats) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

type EmailStatsDateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStatsDateRange) Reset() {
	*x = EmailStatsDateRange{}
	mi := &file_proto_email_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStatsDateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStatsDateRange) ProtoMessage() {}

func (x *EmailStatsDateRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStatsDateRange.ProtoReflect.Descriptor instead.
func (*EmailStatsDateRange) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{32}
}

func (x *EmailStatsDateRange) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *EmailStatsDateRange) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type EmailStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSent     int64                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,2,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalPending  int64                  `protobuf:"varint,4,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	FailureRate   float64                `protobuf:"fixed64,6,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
	AvgRetryCount float64                `protobuf:"fixed64,7,opt,name=avg_retry_count,json=avgRetryCount,proto3" json:"avg_retry_count,omitempty"`
	GroupedStats  []*EmailStatsGroup     `protobuf:"bytes,8,rep,name=grouped_stats,json=groupedStats,proto3" json:"grouped_stats,omitempty"`
	ProviderStats []*EmailProviderStats  `protobuf:"bytes,9,rep,name=provider_stats,json=providerStats,proto3" json:"provider_stats,omitempty"`
	TemplateStats []*EmailTemplateStats  `protobuf:"bytes,10,rep,name=template_stats,json=templateStats,proto3" json:"template_stats,omitempty"`
	DateRange     *EmailStatsDateRange   `protobuf:"bytes,11,opt,name=date_range,json=dateRange,proto3,oneof" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStats) Reset() {
	*x = EmailStats{}
	mi := &file_proto_email_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStats) ProtoMessage() {}

func (x *EmailStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStats.ProtoReflect.Descriptor instead.
func (*EmailStats) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{33}
}

func (x *EmailStats) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *EmailStats) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *EmailStats) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *EmailStats) GetTotalPending() int64 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *EmailStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *EmailStats) GetFailureRate() float64 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

func (x *EmailStats) GetAvgRetryCount() float64 {
	if x != nil {
		return x.AvgRetryCount
	}
	return 0
}

func (x *EmailStats) GetGroupedStats() []*EmailStatsGroup {
	if x != nil {
		return x.GroupedStats
	}
	return nil
}

func (x *EmailStats) GetProviderStats() []*EmailProviderStats {
	if x != nil {
		return x.ProviderStats
	}
	return nil
}

func (x *EmailStats) GetTemplateStats() []*EmailTemplateStats {
	if x != nil {
		return x.TemplateStats
	}
	return nil
}

func (x *EmailStats) GetDateRange() *EmailStatsDateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type GetEmailStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *EmailStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailStatsResponse) Reset() {
	*x = GetEmailStatsResponse{}
	mi := &file_proto_email_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailStatsResponse) ProtoMessage() {}

func (x *GetEmailStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailStatsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{34}
}

func (x *GetEmailStatsResponse) GetStats() *EmailStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_email_proto protoreflect.FileDescriptor

const file_proto_email_proto_rawDesc = "" +
	"\n" +
	"\x11proto/email.proto\x12\aemailpb\"\x89\x05\n" +
	"\bEmailLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x04 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1a\n" +
	"\btemplate\x18\a \x01(\tR\btemplate\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\n" +
	" \x01(\tR\berrorMsg\x12\x17\n" +
	"\asent_at\x18\v \x01(\x03R\x06sentAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\f \x01(\tR\trequestId\x12\x1f\n" +
	"\vretry_count\x18\r \x01(\x05R\n" +
	"retryCount\x12\x18\n" +
	"\aheaders\x18\x0e \x01(\tR\aheaders\x12\x1a\n" +
	"\bresponse\x18\x0f \x01(\tR\bresponse\x12\x1a\n" +
	"\bprovider\x18\x10 \x01(\tR\bprovider\x12)\n" +
	"\x10total_recipients\x18\x11 \x01(\x05R\x0ftotalRecipients\x12!\n" +
	"\fcontent_type\x18\x12 \x01(\tR\vcontentType\x12)\n" +
	"\x10attachment_count\x18\x13 \x01(\x05R\x0fattachmentCount\x12!\n" +
	"\fmessage_size\x18\x14 \x01(\x03R\vmessageSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x17 \x01(\x03R\tdeletedAt\"\xaf\x02\n" +
	"\rEmailTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06locale\x18\b \x01(\tR\x06locale\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\x03R\tdeletedAt\"\xa1\x01\n" +
	"\x0fEmailAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06inline\x18\x04 \x01(\bR\x06inline\x12\x1d\n" +
	"\n" +
	"content_id\x18\x05 \x01(\tR\tcontentId\"\x90\x03\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x02 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x03 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12:\n" +
	"\vattachments\x18\a \x03(\v2\x18.emailpb.EmailAttachmentR\vattachments\x12@\n" +
	"\aheaders\x18\b \x03(\v2&.emailpb.SendEmailRequest.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bprovider\x18\t \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x11SendEmailResponse\x12.\n" +
	"\temail_log\x18\x01 \x01(\v2\x11.emailpb.EmailLogR\bemailLog\"\xa2\x03\n" +
	"\x1cSendEmailWithTemplateRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x02 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x03 \x03(\tR\x03bcc\x12#\n" +
	"\rtemplate_code\x18\x04 \x01(\tR\ftemplateCode\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12:\n" +
	"\vattachments\x18\a \x03(\v2\x18.emailpb.EmailAttachmentR\vattachments\x12L\n" +
	"\aheaders\x18\b \x03(\v22.emailpb.SendEmailWithTemplateRequest.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bprovider\x18\t \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x1dSendEmailWithTemplateResponse\x12.\n" +
	"\temail_log\x18\x01 \x01(\v2\x11.emailpb.EmailLogR\bemailLog\"8\n" +
	"\x12BulkEmailRecipient\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\xcb\x01\n" +
	"\x14SendBulkEmailRequest\x12;\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1b.emailpb.BulkEmailRecipientR\n" +
	"recipients\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"I\n" +
	"\x15SendBulkEmailResponse\x120\n" +
	"\n" +
	"email_logs\x18\x01 \x03(\v2\x11.emailpb.EmailLogR\temailLogs\"6\n" +
	"\x12ResendEmailRequest\x12 \n" +
	"\femail_log_id\x18\x01 \x01(\tR\n" +
	"emailLogId\"E\n" +
	"\x13ResendEmailResponse\x12.\n" +
	"\temail_log\x18\x01 \x01(\v2\x11.emailpb.EmailLogR\bemailLog\"\xe2\x01\n" +
	"\x1aCreateEmailTemplateRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12 \n" +
	"\tis_active\x18\a \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"Q\n" +
	"\x1bCreateEmailTemplateResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.emailpb.EmailTemplateR\btemplate\":\n" +
	"\x17GetEmailTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"N\n" +
	"\x18GetEmailTemplateResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.emailpb.EmailTemplateR\btemplate\"K\n" +
	"\x1dGetEmailTemplateByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"T\n" +
	"\x1eGetEmailTemplateByCodeResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.emailpb.EmailTemplateR\btemplate\"\x9c\x02\n" +
	"\x1aUpdateEmailTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\x03 \x01(\tH\x01R\asubject\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x04 \x01(\tH\x02R\acontent\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x04R\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_subjectB\n" +
	"\n" +
	"\b_contentB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_is_active\"Q\n" +
	"\x1bUpdateEmailTemplateResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.emailpb.EmailTemplateR\btemplate\"=\n" +
	"\x1aDeleteEmailTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"7\n" +
	"\x1bDeleteEmailTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xec\x01\n" +
	"\x19ListEmailTemplatesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x17\n" +
	"\x04code\x18\x03 \x01(\tH\x00R\x04code\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\x04 \x01(\tH\x01R\x06locale\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x05 \x01(\bH\x02R\bisActive\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x06 \x01(\tH\x03R\x06search\x88\x01\x01B\a\n" +
	"\x05_codeB\t\n" +
	"\a_localeB\f\n" +
	"\n" +
	"_is_activeB\t\n" +
	"\a_search\"\xc3\x01\n" +
	"\x1aListEmailTemplatesResponse\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.emailpb.EmailTemplateR\ttemplates\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"6\n" +
	"\x12GetEmailLogRequest\x12 \n" +
	"\femail_log_id\x18\x01 \x01(\tR\n" +
	"emailLogId\"E\n" +
	"\x13GetEmailLogResponse\x12.\n" +
	"\temail_log\x18\x01 \x01(\v2\x11.emailpb.EmailLogR\bemailLog\"\x96\x03\n" +
	"\x14ListEmailLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x04 \x01(\tH\x01R\bprovider\x88\x01\x01\x12\x1f\n" +
	"\btemplate\x18\x05 \x01(\tH\x02R\btemplate\x88\x01\x01\x12(\n" +
	"\rany_recipient\x18\x06 \x01(\tH\x03R\fanyRecipient\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\a \x01(\tH\x04R\x06search\x88\x01\x01\x12\"\n" +
	"\n" +
	"sent_after\x18\b \x01(\x03H\x05R\tsentAfter\x88\x01\x01\x12$\n" +
	"\vsent_before\x18\t \x01(\x03H\x06R\n" +
	"sentBefore\x88\x01\x01B\t\n" +
	"\a_statusB\v\n" +
	"\t_providerB\v\n" +
	"\t_templateB\x10\n" +
	"\x0e_any_recipientB\t\n" +
	"\a_searchB\r\n" +
	"\v_sent_afterB\x0e\n" +
	"\f_sent_before\"\xba\x01\n" +
	"\x15ListEmailLogsResponse\x120\n" +
	"\n" +
	"email_logs\x18\x01 \x03(\v2\x11.emailpb.EmailLogR\temailLogs\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xdd\x02\n" +
	"\x14GetEmailStatsRequest\x12\x1f\n" +
	"\bprovider\x18\x01 \x01(\tH\x00R\bprovider\x88\x01\x01\x12\x1f\n" +
	"\btemplate\x18\x02 \x01(\tH\x01R\btemplate\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01\x12 \n" +
	"\tdate_from\x18\x04 \x01(\x03H\x03R\bdateFrom\x88\x01\x01\x12\x1c\n" +
	"\adate_to\x18\x05 \x01(\x03H\x04R\x06dateTo\x88\x01\x01\x12\x1e\n" +
	"\bgroup_by\x18\x06 \x01(\tH\x05R\agroupBy\x88\x01\x01\x12(\n" +
	"\rinclude_total\x18\a \x01(\bH\x06R\fincludeTotal\x88\x01\x01B\v\n" +
	"\t_providerB\v\n" +
	"\t_templateB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\v\n" +
	"\t_group_byB\x10\n" +
	"\x0e_include_total\"\xc3\x01\n" +
	"\x0fEmailStatsGroup\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x12\n" +
	"\x04sent\x18\x04 \x01(\x03R\x04sent\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\x03R\asuccess\x12\x16\n" +
	"\x06failed\x18\x06 \x01(\x03R\x06failed\x12\x18\n" +
	"\apending\x18\a \x01(\x03R\apending\x12\x12\n" +
	"\x04rate\x18\b \x01(\x01R\x04rate\"\xe2\x01\n" +
	"\x12EmailProviderStats\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x02 \x01(\x03R\ttotalSent\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x04 \x01(\x03R\vtotalFailed\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x12&\n" +
	"\x0favg_retry_count\x18\x06 \x01(\x01R\ravgRetryCount\"\xeb\x01\n" +
	"\x12EmailTemplateStats\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x03 \x01(\x03R\ttotalSent\x12#\n" +
	"\rtotal_success\x18\x04 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x05 \x01(\x03R\vtotalFailed\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12\x1b\n" +
	"\tlast_used\x18\a \x01(\x03R\blastUsed\"9\n" +
	"\x13EmailStatsDateRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\"\x9e\x04\n" +
	"\n" +
	"EmailStats\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x03R\ttotalSent\x12#\n" +
	"\rtotal_success\x18\x02 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x03R\vtotalFailed\x12#\n" +
	"\rtotal_pending\x18\x04 \x01(\x03R\ftotalPending\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x12!\n" +
	"\ffailure_rate\x18\x06 \x01(\x01R\vfailureRate\x12&\n" +
	"\x0favg_retry_count\x18\a \x01(\x01R\ravgRetryCount\x12=\n" +
	"\rgrouped_stats\x18\b \x03(\v2\x18.emailpb.EmailStatsGroupR\fgroupedStats\x12B\n" +
	"\x0eprovider_stats\x18\t \x03(\v2\x1b.emailpb.EmailProviderStatsR\rproviderStats\x12B\n" +
	"\x0etemplate_stats\x18\n" +
	" \x03(\v2\x1b.emailpb.EmailTemplateStatsR\rtemplateStats\x12@\n" +
	"\n" +
	"date_range\x18\v \x01(\v2\x1c.emailpb.EmailStatsDateRangeH\x00R\tdateRange\x88\x01\x01B\r\n" +
	"\v_date_range\"B\n" +
	"\x15GetEmailStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.emailpb.EmailStatsR\x05stats2\x87\t\n" +
	"\fEmailService\x12B\n" +
	"\tSendEmail\x12\x19.emailpb.SendEmailRequest\x1a\x1a.emailpb.SendEmailResponse\x12f\n" +
	"\x15SendEmailWithTemplate\x12%.emailpb.SendEmailWithTemplateRequest\x1a&.emailpb.SendEmailWithTemplateResponse\x12N\n" +
	"\rSendBulkEmail\x12\x1d.emailpb.SendBulkEmailRequest\x1a\x1e.emailpb.SendBulkEmailResponse\x12H\n" +
	"\vResendEmail\x12\x1b.emailpb.ResendEmailRequest\x1a\x1c.emailpb.ResendEmailResponse\x12`\n" +
	"\x13CreateEmailTemplate\x12#.emailpb.CreateEmailTemplateRequest\x1a$.emailpb.CreateEmailTemplateResponse\x12W\n" +
	"\x10GetEmailTemplate\x12 .emailpb.GetEmailTemplateRequest\x1a!.emailpb.GetEmailTemplateResponse\x12i\n" +
	"\x16GetEmailTemplateByCode\x12&.emailpb.GetEmailTemplateByCodeRequest\x1a'.emailpb.GetEmailTemplateByCodeResponse\x12`\n" +
	"\x13UpdateEmailTemplate\x12#.emailpb.UpdateEmailTemplateRequest\x1a$.emailpb.UpdateEmailTemplateResponse\x12`\n" +
	"\x13DeleteEmailTemplate\x12#.emailpb.DeleteEmailTemplateRequest\x1a$.emailpb.DeleteEmailTemplateResponse\x12]\n" +
	"\x12ListEmailTemplates\x12\".emailpb.ListEmailTemplatesRequest\x1a#.emailpb.ListEmailTemplatesResponse\x12H\n" +
	"\vGetEmailLog\x12\x1b.emailpb.GetEmailLogRequest\x1a\x1c.emailpb.GetEmailLogResponse\x12N\n" +
	"\rListEmailLogs\x12\x1d.emailpb.ListEmailLogsRequest\x1a\x1e.emailpb.ListEmailLogsResponse\x12N\n" +
	"\rGetEmailStats\x12\x1d.emailpb.GetEmailStatsRequest\x1a\x1e.emailpb.GetEmailStatsResponseB\rZ\vproto/pb;pbb\x06proto3"

var (
	file_proto_email_proto_rawDescOnce sync.Once
	file_proto_email_proto_rawDescData []byte
)

func file_proto_email_proto_rawDescGZIP() []byte {
	file_proto_email_proto_rawDescOnce.Do(func() {
		file_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_proto_rawDesc), len(file_proto_email_proto_rawDesc)))
	})
	return file_proto_email_proto_rawDescData
}

var file_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_email_proto_goTypes = []any{
	(*EmailLog)(nil),                       // 0: emailpb.EmailLog
	(*EmailTemplate)(nil),                  // 1: emailpb.EmailTemplate
	(*EmailAttachment)(nil),                // 2: emailpb.EmailAttachment
	(*SendEmailRequest)(nil),               // 3: emailpb.SendEmailRequest
	(*SendEmailResponse)(nil),              // 4: emailpb.SendEmailResponse
	(*SendEmailWithTemplateRequest)(nil),   // 5: emailpb.SendEmailWithTemplateRequest
	(*SendEmailWithTemplateResponse)(nil),  // 6: emailpb.SendEmailWithTemplateResponse
	(*BulkEmailRecipient)(nil),             // 7: emailpb.BulkEmailRecipient
	(*SendBulkEmailRequest)(nil),           // 8: emailpb.SendBulkEmailRequest
	(*SendBulkEmailResponse)(nil),          // 9: emailpb.SendBulkEmailResponse
	(*ResendEmailRequest)(nil),             // 10: emailpb.ResendEmailRequest
	(*ResendEmailResponse)(nil),            // 11: emailpb.ResendEmailResponse
	(*CreateEmailTemplateRequest)(nil),     // 12: emailpb.CreateEmailTemplateRequest
	(*CreateEmailTemplateResponse)(nil),    // 13: emailpb.CreateEmailTemplateResponse
	(*GetEmailTemplateRequest)(nil),        // 14: emailpb.GetEmailTemplateRequest
	(*GetEmailTemplateResponse)(nil),       // 15: emailpb.GetEmailTemplateResponse
	(*GetEmailTemplateByCodeRequest)(nil),  // 16: emailpb.GetEmailTemplateByCodeRequest
	(*GetEmailTemplateByCodeResponse)(nil), // 17: emailpb.GetEmailTemplateByCodeResponse
	(*UpdateEmailTemplateRequest)(nil),     // 18: emailpb.UpdateEmailTemplateRequest
	(*UpdateEmailTemplateResponse)(nil),    // 19: emailpb.UpdateEmailTemplateResponse
	(*DeleteEmailTemplateRequest)(nil),     // 20: emailpb.DeleteEmailTemplateRequest
	(*DeleteEmailTemplateResponse)(nil),    // 21: emailpb.DeleteEmailTemplateResponse
	(*ListEmailTemplatesRequest)(nil),      // 22: emailpb.ListEmailTemplatesRequest
	(*ListEmailTemplatesResponse)(nil),     // 23: emailpb.ListEmailTemplatesResponse
	(*GetEmailLogRequest)(nil),             // 24: emailpb.GetEmailLogRequest
	(*GetEmailLogResponse)(nil),            // 25: emailpb.GetEmailLogResponse
	(*ListEmailLogsRequest)(nil),           // 26: emailpb.ListEmailLogsRequest
	(*ListEmailLogsResponse)(nil),          // 27: emailpb.ListEmailLogsResponse
	(*GetEmailStatsRequest)(nil),           // 28: emailpb.GetEmailStatsRequest
	(*EmailStatsGroup)(nil),                // 29: emailpb.EmailStatsGroup
	(*EmailProviderStats)(nil),             // 30: emailpb.EmailProviderStats
	(*EmailTemplateStats)(nil),             // 31: emailpb.EmailTemplateStats
	(*EmailStatsDateRange)(nil),            // 32: emailpb.EmailStatsDateRange
	(*EmailStats)(nil),                     // 33: emailpb.EmailStats
	(*GetEmailStatsResponse)(nil),          // 34: emailpb.GetEmailStatsResponse
	nil,                                    // 35: emailpb.SendEmailRequest.HeadersEntry
	nil,                                    // 36: emailpb.SendEmailWithTemplateRequest.HeadersEntry
}
var file_proto_email_proto_depIdxs = []int32{
	2,  // 0: emailpb.SendEmailRequest.attachments:type_name -> emailpb.EmailAttachment
	35, // 1: emailpb.SendEmailRequest.headers:type_name -> emailpb.SendEmailRequest.HeadersEntry
	0,  // 2: emailpb.SendEmailResponse.email_log:type_name -> emailpb.EmailLog
	2,  // 3: emailpb.SendEmailWithTemplateRequest.attachments:type_name -> emailpb.EmailAttachment
	36, // 4: emailpb.SendEmailWithTemplateRequest.headers:type_name -> emailpb.SendEmailWithTemplateRequest.HeadersEntry
	0,  // 5: emailpb.SendEmailWithTemplateResponse.email_log:type_name -> emailpb.EmailLog
	7,  // 6: emailpb.SendBulkEmailRequest.recipients:type_name -> emailpb.BulkEmailRecipient
	0,  // 7: emailpb.SendBulkEmailResponse.email_logs:type_name -> emailpb.EmailLog
	0,  // 8: emailpb.ResendEmailResponse.email_log:type_name -> emailpb.EmailLog
	1,  // 9: emailpb.CreateEmailTemplateResponse.template:type_name -> emailpb.EmailTemplate
	1,  // 10: emailpb.GetEmailTemplateResponse.template:type_name -> emailpb.EmailTemplate
	1,  // 11: emailpb.GetEmailTemplateByCodeResponse.template:type_name -> emailpb.EmailTemplate
	1,  // 12: emailpb.UpdateEmailTemplateResponse.template:type_name -> emailpb.EmailTemplate
	1,  // 13: emailpb.ListEmailTemplatesResponse.templates:type_name -> emailpb.EmailTemplate
	0,  // 14: emailpb.GetEmailLogResponse.email_log:type_name -> emailpb.EmailLog
	0,  // 15: emailpb.ListEmailLogsResponse.email_logs:type_name -> emailpb.EmailLog
	29, // 16: emailpb.EmailStats.grouped_stats:type_name -> emailpb.EmailStatsGroup
	30, // 17: emailpb.EmailStats.provider_stats:type_name -> emailpb.EmailProviderStats
	31, // 18: emailpb.EmailStats.template_stats:type_name -> emailpb.EmailTemplateStats
	32, // 19: emailpb.EmailStats.date_range:type_name -> emailpb.EmailStatsDateRange
	33, // 20: emailpb.GetEmailStatsResponse.stats:type_name -> emailpb.EmailStats
	3,  // 21: emailpb.EmailService.SendEmail:input_type -> emailpb.SendEmailRequest
	5,  // 22: emailpb.EmailService.SendEmailWithTemplate:input_type -> emailpb.SendEmailWithTemplateRequest
	8,  // 23: emailpb.EmailService.SendBulkEmail:input_type -> emailpb.SendBulkEmailRequest
	10, // 24: emailpb.EmailService.ResendEmail:input_type -> emailpb.ResendEmailRequest
	12, // 25: emailpb.EmailService.CreateEmailTemplate:input_type -> emailpb.CreateEmailTemplateRequest
	14, // 26: emailpb.EmailService.GetEmailTemplate:input_type -> emailpb.GetEmailTemplateRequest
	16, // 27: emailpb.EmailService.GetEmailTemplateByCode:input_type -> emailpb.GetEmailTemplateByCodeRequest
	18, // 28: emailpb.EmailService.UpdateEmailTemplate:input_type -> emailpb.UpdateEmailTemplateRequest
	20, // 29: emailpb.EmailService.DeleteEmailTemplate:input_type -> emailpb.DeleteEmailTemplateRequest
	22, // 30: emailpb.EmailService.ListEmailTemplates:input_type -> emailpb.ListEmailTemplatesRequest
	24, // 31: emailpb.EmailService.GetEmailLog:input_type -> emailpb.GetEmailLogRequest
	26, // 32: emailpb.EmailService.ListEmailLogs:input_type -> emailpb.ListEmailLogsRequest
	28, // 33: emailpb.EmailService.GetEmailStats:input_type -> emailpb.GetEmailStatsRequest
	4,  // 34: emailpb.EmailService.SendEmail:output_type -> emailpb.SendEmailResponse
	6,  // 35: emailpb.EmailService.SendEmailWithTemplate:output_type -> emailpb.SendEmailWithTemplateResponse
	9,  // 36: emailpb.EmailService.SendBulkEmail:output_type -> emailpb.SendBulkEmailResponse
	11, // 37: emailpb.EmailService.ResendEmail:output_type -> emailpb.ResendEmailResponse
	13, // 38: emailpb.EmailService.CreateEmailTemplate:output_type -> emailpb.CreateEmailTemplateResponse
	15, // 39: emailpb.EmailService.GetEmailTemplate:output_type -> emailpb.GetEmailTemplateResponse
	17, // 40: emailpb.EmailService.GetEmailTemplateByCode:output_type -> emailpb.GetEmailTemplateByCodeResponse
	19, // 41: emailpb.EmailService.UpdateEmailTemplate:output_type -> emailpb.UpdateEmailTemplateResponse
	21, // 42: emailpb.EmailService.DeleteEmailTemplate:output_type -> emailpb.DeleteEmailTemplateResponse
	23, // 43: emailpb.EmailService.ListEmailTemplates:output_type -> emailpb.ListEmailTemplatesResponse
	25, // 44: emailpb.EmailService.GetEmailLog:output_type -> emailpb.GetEmailLogResponse
	27, // 45: emailpb.EmailService.ListEmailLogs:output_type -> emailpb.ListEmailLogsResponse
	34, // 46: emailpb.EmailService.GetEmailStats:output_type -> emailpb.GetEmailStatsResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_email_proto_init() }
func file_proto_email_proto_init() {
	if File_proto_email_proto != nil {
		return
	}
	file_proto_email_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_email_proto_msgTypes[18].OneofWrappers = []any{}
	file_proto_email_proto_msgTypes[22].OneofWrappers = []any{}
	file_proto_email_proto_msgTypes[26].OneofWrappers = []any{}
	file_proto_email_proto_msgTypes[28].OneofWrappers = []any{}
	file_proto_email_proto_msgTypes[33].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_proto_rawDesc), len(file_proto_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_proto_goTypes,
		DependencyIndexes: file_proto_email_proto_depIdxs,
		MessageInfos:      file_proto_email_proto_msgTypes,
	}.Build()
	File_proto_email_proto = out.File
	file_proto_email_proto_goTypes = nil
	file_proto_email_proto_depIdxs = nil
}
